name: Check for readme-changes

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  GH_TOKEN: ${{ secrets.PR_COMMENT }}

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout
        id: checkout
        uses: actions/checkout@v2.3.3

      - name: Add Changeset Comment
        id: add-comment
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          REPO_OWNER=$(echo "${{ github.repository_owner }}")
          REPO_NAME=$(echo "${{ github.repository }}")
          PR_HEAD_SHA=$(echo "${{ github.event.pull_request.head.sha }}")

          echo PR_NUMBER
          
          CHANGED_FILES=$(curl -s -H "Authorization: Bearer ${{ env.GH_TOKEN }}" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/pulls/$PR_NUMBER/files" \
            | jq -r '.[].filename')
          
          echo CHANGED_FILES_URL: "https://api.github.com/repos/$REPO_NAME/pulls/$PR_NUMBER/files"
          echo CHANGED_FILES: $CHANGED_FILES
          
          CHANGES_COUNT=$(echo "$CHANGED_FILES" | grep -c "^\README/.*\.md$" || true)

          echo CHANGES_COUNT: $CHANGES_COUNT
          if [[ $CHANGES_COUNT -gt 0 ]]; then
            COMMENT="<h3>Readme changes detected</h3><p><b>The changes are detected for the README file.</b></p>"
          else
            COMMENT="<h3>No Readme changes found</h3><p>Merging this PR will not cause a version bump for any packages. If these changes should not result in a new version, you're good to go.</p>"
          fi
          
          GITHUB_API="https://api.github.com"
          COMMENTS_URL="$GITHUB_API/repos/$REPO_NAME/issues/$PR_NUMBER/comments"
          echo COMMENTS_URL: "$COMMENTS_URL"
          COMMENT_BODY=$(jq --null-input --arg body "$COMMENT" '{"body": $body}')
          curl -s -H "Authorization: Bearer ${{ env.GH_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Content-Type: application/json" \
            -d "$COMMENT_BODY" \
            "$COMMENTS_URL"

#          echo "Checking for changes in README.md"
#          if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q "README.md"; then
#            echo "Changes found in README.md"
#            curl -X POST -H "Authorization: token $GH_TOKEN" -d '{"body": "📝 Changes found in README.md"}' "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
#          else
#            echo "No changes found in README.md"
#          fi
